#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
toreport

Parses ical entries for time off entries to produce a report of time off taken
and remaining
"""

import argparse
import yaml
from icalevents import icalevents
import sys
import datetime
import pytz

class ToreportException(Exception):
    pass

def toreport(cfgfile):
    try:
        with open(cfgfile, 'r') as yamlfile:
            config = yaml.safe_load(yamlfile)
    except IOError as err:
        raise ToreportException(err)

    year = config['year']

    events = icalevents.events(config['url'],
                               fix_apple='icloud' in config['url'],
                               start=datetime.date(year, 1, 1),
                               end=datetime.date(year,12,31))

    to_lists = dict()

    to_types = config['types'].keys()

    for to_type in to_types:
        to_lists[to_type] = list()

    for event in events:
        print(event.summary)
        if event.summary in to_types and event.start.year == year:
            to_lists[event.summary].append(event)

    print(to_lists)
    today = datetime.date.today()

    for to_type in to_lists.keys():
        type_hours_used = 0
        type_hours_scheduled = 0

        print("Calculating {}".format(to_type))

        to_lists[to_type].sort(key=lambda x: x.start if x.start.tzinfo else pytz.utc.localize(x.start))

        for event in to_lists[to_type]:
            if event.all_day:
                hours = 8
            else:
                hours = int((event.end - event.start)/datetime.timedelta(hours=1))

            print("{} hours on {}".format(hours, event.start.date().strftime("%a %b %d")))

            if event.start.date() < today:
                type_hours_used += hours
            else:
                type_hours_scheduled += hours

        remaining_hours = config['types'][to_type]['available'] -\
                          (type_hours_used + type_hours_scheduled)

        print("Used {}".format(type_hours_used))
        print("Scheduled {}".format(type_hours_scheduled))
        print("{} days ({} hours) of {} remain in {}".format(remaining_hours / 8,
            remaining_hours, to_type, year))

if __name__ == '__main__':
    def main(cmdln_args):
        """
        Set up and parse arguments

        Arguments:
            cmdln_args: List of command line arguments (excluding script name)
        """

        # Parse arguments with argparse
        formatter_class = argparse.ArgumentDefaultsHelpFormatter

        parser = argparse.ArgumentParser(description=__doc__,
                                         formatter_class=formatter_class)

        parser.add_argument('--cfgfile',
                            help="Configuration file",
                            type=str,
                            default='toreport.yaml')

        args = parser.parse_args(cmdln_args)

        try:
            toreport(args.cfgfile)
        except ToreportException as err:
            print(err)
            return 1

        return 0

    # Call main() with parsed args
    sys.exit(main(sys.argv[1:]))